<a href="https://colab.research.google.com/github/asrianda/matakuliah/blob/main/Kecerdasan_K_MTI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import MinMaxScaler

# Dataset
X = np.array([
    [2, 60, 50],
    [3, 65, 55],
    [4, 70, 60],
    [5, 75, 65],
    [6, 80, 70],
    [7, 85, 75],
    [8, 90, 80],
    [1, 50, 45],
    [9, 95, 85],
    [10, 98, 90]
])

y = np.array([0,0,0,1,1,1,1,0,1,1])

# Normalisasi (lebih standar pakai scaler)
scaler = MinMaxScaler()
X = scaler.fit_transform(X)

# Model Neural Network
model = MLPClassifier(
    hidden_layer_sizes=(4,),   # 1 hidden layer, 4 neuron
    activation='relu',
    solver='adam',
    max_iter=1000,
    random_state=42
)

# Training
model.fit(X, y)

# Prediksi
pred = model.predict(X)

# Probabilitas
prob = model.predict_proba(X)

print("Probabilitas:")
print(prob)

print("\nPrediksi kelas:")
print(pred)

Probabilitas:
[[0.87135617 0.12864383]
 [0.74382898 0.25617102]
 [0.55451456 0.44548544]
 [0.34793947 0.65206053]
 [0.18616167 0.81383833]
 [0.08930232 0.91069768]
 [0.05898293 0.94101707]
 [0.93075015 0.06924985]
 [0.03852402 0.96147598]
 [0.02535707 0.97464293]]

Prediksi kelas:
[0 0 0 1 1 1 1 0 1 1]


/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


## **Neural Network**

In [2]:
import numpy as np

# Dataset
X = np.array([
    [2, 60, 50],
    [3, 65, 55],
    [4, 70, 60],
    [5, 75, 65],
    [6, 80, 70],
    [7, 85, 75],
    [8, 90, 80],
    [1, 50, 45],
    [9, 95, 85],
    [10, 98, 90]
])

y = np.array([[0],[0],[0],[1],[1],[1],[1],[0],[1],[1]])

# Normalisasi
X = X / np.max(X, axis=0)

# Inisialisasi bobot
np.random.seed(1)
weights_input_hidden = np.random.rand(3, 2)
weights_hidden_output = np.random.rand(2, 1)

bias_hidden = np.random.rand(1, 2)
bias_output = np.random.rand(1, 1)

# Fungsi aktivasi
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Training
epochs = 5000
lr = 0.1

for i in range(epochs):

    # FORWARD
    hidden = sigmoid(np.dot(X, weights_input_hidden) + bias_hidden)
    output = sigmoid(np.dot(hidden, weights_hidden_output) + bias_output)

    # ERROR
    error = y - output

    # BACKPROPAGATION
    d_output = error * sigmoid_derivative(output)
    d_hidden = d_output.dot(weights_hidden_output.T) * sigmoid_derivative(hidden)

    # UPDATE
    weights_hidden_output += hidden.T.dot(d_output) * lr
    weights_input_hidden += X.T.dot(d_hidden) * lr

    bias_output += np.sum(d_output, axis=0) * lr
    bias_hidden += np.sum(d_hidden, axis=0) * lr

# HASIL
print("Output prediksi:")
print(output)

print("\nPrediksi kelas:")
print((output > 0.5).astype(int))

Output prediksi:
[[0.00729707]
 [0.02461055]
 [0.19252006]
 [0.81844134]
 [0.98147281]
 [0.99557942]
 [0.99787929]
 [0.00395728]
 [0.99855846]
 [0.9988444 ]]

Prediksi kelas:
[[0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]]


## **Deep Learning**

In [3]:
import numpy as np

# =========================
# 1. DATA INPUT
# =========================

# Normalisasi data
x1 = 0.2
x2 = 0.5

# Target
target = 0

# =========================
# 2. INISIALISASI BOBOT
# =========================

# Input -> Hidden
w1 = 0.1
w2 = 0.2
w3 = 0.3
w4 = 0.4

# Bias hidden
b1 = 0.1
b2 = 0.1

# Hidden -> Output
w5 = 0.5
w6 = 0.6

# Bias output
b3 = 0.1

# Learning rate
alpha = 0.1

# =========================
# 3. FUNGSI SIGMOID
# =========================

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# =========================
# 4. FORWARD PROPAGATION
# =========================

print("=== FORWARD PROPAGATION ===")

# Hidden neuron 1
zh1 = (w1 * x1) + (w2 * x2) + b1
h1 = sigmoid(zh1)

print("\nHidden Neuron 1")
print("zh1 =", round(zh1, 4))
print("h1 =", round(h1, 4))

# Hidden neuron 2
zh2 = (w3 * x1) + (w4 * x2) + b2
h2 = sigmoid(zh2)

print("\nHidden Neuron 2")
print("zh2 =", round(zh2, 4))
print("h2 =", round(h2, 4))

# Output neuron
zo = (w5 * h1) + (w6 * h2) + b3
y_pred = sigmoid(zo)

print("\nOutput Layer")
print("zo =", round(zo, 4))
print("y_pred =", round(y_pred, 4))

# =========================
# 5. HITUNG ERROR
# =========================

print("\n=== ERROR ===")

error = 0.5 * ((target - y_pred) ** 2)

print("Error =", round(error, 4))

# =========================
# 6. BACKPROPAGATION
# =========================

print("\n=== BACKPROPAGATION ===")

# Delta output
delta_o = (target - y_pred) * y_pred * (1 - y_pred)

print("\nDelta Output")
print("delta_o =", round(delta_o, 4))

# =========================
# 7. UPDATE HIDDEN -> OUTPUT
# =========================

print("\nUpdate Bobot Hidden -> Output")

w5_new = w5 + (alpha * delta_o * h1)
w6_new = w6 + (alpha * delta_o * h2)

print("w5 lama =", w5)
print("w5 baru =", round(w5_new, 4))

print("w6 lama =", w6)
print("w6 baru =", round(w6_new, 4))

# =========================
# 8. DELTA HIDDEN
# =========================

delta_h1 = h1 * (1 - h1) * (delta_o * w5)
delta_h2 = h2 * (1 - h2) * (delta_o * w6)

print("\nDelta Hidden")
print("delta_h1 =", round(delta_h1, 4))
print("delta_h2 =", round(delta_h2, 4))

# =========================
# 9. UPDATE INPUT -> HIDDEN
# =========================

print("\nUpdate Bobot Input -> Hidden")

w1_new = w1 + (alpha * delta_h1 * x1)
w2_new = w2 + (alpha * delta_h1 * x2)

w3_new = w3 + (alpha * delta_h2 * x1)
w4_new = w4 + (alpha * delta_h2 * x2)

print("\nw1 lama =", w1)
print("w1 baru =", round(w1_new, 4))

print("\nw2 lama =", w2)
print("w2 baru =", round(w2_new, 4))

print("\nw3 lama =", w3)
print("w3 baru =", round(w3_new, 4))

print("\nw4 lama =", w4)
print("w4 baru =", round(w4_new, 4))

# =========================
# 10. HASIL AKHIR
# =========================

print("\n=== HASIL AKHIR ITERASI ===")

print(f"w1 : {w1} -> {round(w1_new,4)}")
print(f"w2 : {w2} -> {round(w2_new,4)}")
print(f"w3 : {w3} -> {round(w3_new,4)}")
print(f"w4 : {w4} -> {round(w4_new,4)}")
print(f"w5 : {w5} -> {round(w5_new,4)}")
print(f"w6 : {w6} -> {round(w6_new,4)}")

=== FORWARD PROPAGATION ===

Hidden Neuron 1
zh1 = 0.22
h1 = 0.5548

Hidden Neuron 2
zh2 = 0.36
h2 = 0.589

Output Layer
zo = 0.7308
y_pred = 0.675

=== ERROR ===
Error = 0.2278

=== BACKPROPAGATION ===

Delta Output
delta_o = -0.1481

Update Bobot Hidden -> Output
w5 lama = 0.5
w5 baru = 0.4918
w6 lama = 0.6
w6 baru = 0.5913

Delta Hidden
delta_h1 = -0.0183
delta_h2 = -0.0215

Update Bobot Input -> Hidden

w1 lama = 0.1
w1 baru = 0.0996

w2 lama = 0.2
w2 baru = 0.1991

w3 lama = 0.3
w3 baru = 0.2996

w4 lama = 0.4
w4 baru = 0.3989

=== HASIL AKHIR ITERASI ===
w1 : 0.1 -> 0.0996
w2 : 0.2 -> 0.1991
w3 : 0.3 -> 0.2996
w4 : 0.4 -> 0.3989
w5 : 0.5 -> 0.4918
w6 : 0.6 -> 0.5913


### **Contoh dengan 100  Record Data**

In [4]:
import numpy as np
import pandas as pd
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# =====================================================
# 1. MEMBUAT DATASET SIMULASI (100 RECORD)
# =====================================================

np.random.seed(42)

jumlah_data = 100

# Fitur
jam_belajar = np.random.randint(1, 11, jumlah_data)
nilai_tugas = np.random.randint(40, 101, jumlah_data)

# Target simulasi
# Jika kombinasi belajar dan tugas tinggi -> lulus
lulus = []

for jam, nilai in zip(jam_belajar, nilai_tugas):

    skor = (jam * 0.4) + (nilai * 0.6)

    if skor >= 50:
        lulus.append(1)
    else:
        lulus.append(0)

# Membuat DataFrame
df = pd.DataFrame({
    'Jam_Belajar': jam_belajar,
    'Nilai_Tugas': nilai_tugas,
    'Lulus': lulus
})

print("=== DATASET SIMULASI ===")
print(df.head())

# =====================================================
# 2. INPUT DAN TARGET
# =====================================================

X = df[['Jam_Belajar', 'Nilai_Tugas']].values
y = df['Lulus'].values

# =====================================================
# 3. NORMALISASI DATA
# =====================================================

scaler = MinMaxScaler()
X = scaler.fit_transform(X)

# =====================================================
# 4. SPLIT DATA TRAINING DAN TESTING
# =====================================================

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

# =====================================================
# 5. MODEL NEURAL NETWORK
# =====================================================

model = MLPClassifier(
    hidden_layer_sizes=(2,),     # 1 hidden layer, 2 neuron
    activation='logistic',       # sigmoid
    solver='sgd',                # gradient descent
    learning_rate_init=0.1,
    max_iter=2000,
    random_state=42
)

# =====================================================
# 6. TRAINING MODEL
# =====================================================

model.fit(X_train, y_train)

# =====================================================
# 7. PREDIKSI
# =====================================================

y_pred = model.predict(X_test)

# Probabilitas
y_prob = model.predict_proba(X_test)

# =====================================================
# 8. HASIL EVALUASI
# =====================================================

print("\n=== HASIL PREDIKSI ===")
print(y_pred)

print("\n=== PROBABILITAS ===")
print(y_prob)

# Accuracy
acc = accuracy_score(y_test, y_pred)

print("\n=== ACCURACY ===")
print("Accuracy :", round(acc, 4))

# Confusion Matrix
print("\n=== CONFUSION MATRIX ===")
print(confusion_matrix(y_test, y_pred))

# Classification Report
print("\n=== CLASSIFICATION REPORT ===")
print(classification_report(y_test, y_pred))

# =====================================================
# 9. BOBOT DAN BIAS
# =====================================================

print("\n=== BOBOT INPUT -> HIDDEN ===")
print(model.coefs_[0])

print("\n=== BOBOT HIDDEN -> OUTPUT ===")
print(model.coefs_[1])

print("\n=== BIAS HIDDEN ===")
print(model.intercepts_[0])

print("\n=== BIAS OUTPUT ===")
print(model.intercepts_[1])

# =====================================================
# 10. PREDIKSI DATA BARU
# =====================================================

data_baru = np.array([[7, 85]])

# Normalisasi data baru
data_baru = scaler.transform(data_baru)

prediksi_baru = model.predict(data_baru)

print("\n=== PREDIKSI DATA BARU ===")
print("Input : Jam Belajar=7, Nilai Tugas=85")

if prediksi_baru[0] == 1:
    print("Prediksi : LULUS")
else:
    print("Prediksi : TIDAK LULUS")

=== DATASET SIMULASI ===
   Jam_Belajar  Nilai_Tugas  Lulus
0            7           51      0
1            4           73      0
2            8           72      0
3            5           87      1
4            7           94      1

=== HASIL PREDIKSI ===
[0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 1 0 0 0 1]

=== PROBABILITAS ===
[[6.59697327e-01 3.40302673e-01]
 [9.99854911e-01 1.45089135e-04]
 [9.99747448e-01 2.52552135e-04]
 [5.91638812e-01 4.08361188e-01]
 [9.96624507e-01 3.37549256e-03]
 [1.49576688e-03 9.98504233e-01]
 [9.90613330e-01 9.38666995e-03]
 [2.04573043e-03 9.97954270e-01]
 [5.51514813e-01 4.48485187e-01]
 [9.99738276e-01 2.61723906e-04]
 [9.99695537e-01 3.04462556e-04]
 [9.92601865e-01 7.39813486e-03]
 [9.94041247e-01 5.95875301e-03]
 [9.99776165e-01 2.23834615e-04]
 [8.73281997e-01 1.26718003e-01]
 [2.95538850e-03 9.97044611e-01]
 [8.77316620e-01 1.22683380e-01]
 [9.99863388e-01 1.36612481e-04]
 [9.91622254e-01 8.37774635e-03]
 [3.95123427e-01 6.04876573e-01]]

=== ACCURACY ==

## **Menggunakan program yang di Slide**

In [5]:
import numpy as np
import pandas as pd
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import MinMaxScaler

# =====================================================
# 1. MEMBUAT DATASET SIMULASI 100 RECORD
# =====================================================

np.random.seed(42)

jumlah_data = 100

# Fitur
jam_belajar = np.random.randint(1, 11, jumlah_data)
nilai_tugas = np.random.randint(40, 101, jumlah_data)

# Target
lulus = []

for jam, nilai in zip(jam_belajar, nilai_tugas):

    skor = (jam * 0.4) + (nilai * 0.6)

    if skor >= 50:
        lulus.append(1)
    else:
        lulus.append(0)

# Dataset
X = np.column_stack((jam_belajar, nilai_tugas))
y = np.array(lulus)

# Menampilkan sebagian dataset
df = pd.DataFrame({
    'Jam_Belajar': jam_belajar,
    'Nilai_Tugas': nilai_tugas,
    'Lulus': lulus
})

print("=== DATASET ===")
print(df.head(10))

# =====================================================
# 2. NORMALISASI
# =====================================================

scaler = MinMaxScaler()
X = scaler.fit_transform(X)

# =====================================================
# 3. MODEL NEURAL NETWORK
# =====================================================

model = MLPClassifier(
    hidden_layer_sizes=(2,),   # 1 hidden layer, 2 neuron
    activation='logistic',     # sigmoid
    solver='sgd',              # gradient descent
    learning_rate_init=0.1,
    max_iter=1000,
    random_state=1
)

# =====================================================
# 4. TRAINING
# =====================================================

model.fit(X, y)

# =====================================================
# 5. PREDIKSI
# =====================================================

pred = model.predict(X)

# Probabilitas
prob = model.predict_proba(X)

# =====================================================
# 6. OUTPUT
# =====================================================

print("\n=== HASIL PREDIKSI ===")
print(pred)

print("\n=== PROBABILITAS ===")
print(prob)

# =====================================================
# 7. BOBOT DAN BIAS
# =====================================================

print("\n=== BOBOT INPUT -> HIDDEN ===")
print(model.coefs_[0])

print("\n=== BOBOT HIDDEN -> OUTPUT ===")
print(model.coefs_[1])

print("\n=== BIAS HIDDEN ===")
print(model.intercepts_[0])

print("\n=== BIAS OUTPUT ===")
print(model.intercepts_[1])

# =====================================================
# 8. ACCURACY
# =====================================================

accuracy = model.score(X, y)

print("\n=== ACCURACY ===")
print(round(accuracy * 100, 2), "%")

# =====================================================
# 9. PREDIKSI DATA BARU
# =====================================================

data_baru = np.array([[7, 85]])

# Normalisasi data baru
data_baru = scaler.transform(data_baru)

hasil = model.predict(data_baru)

print("\n=== PREDIKSI DATA BARU ===")

print("Input:")
print("Jam Belajar = 7")
print("Nilai Tugas = 85")

if hasil[0] == 1:
    print("Prediksi = LULUS")
else:
    print("Prediksi = TIDAK LULUS")

=== DATASET ===
   Jam_Belajar  Nilai_Tugas  Lulus
0            7           51      0
1            4           73      0
2            8           72      0
3            5           87      1
4            7           94      1
5           10           62      0
6            3           63      0
7            7           76      0
8            8           74      0
9            5           83      1

=== HASIL PREDIKSI ===
[0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 1 0 1
 1 1 1 0 0 0 0 0 0 1 0 1 0 0 0 0 0 1 1 0 0 0 1 1 1 1 0 0 0 1 1 0 0 0 1 1 0
 0 1 0 0 1 0 1 1 0 0 0 1 0 0 0 0 0 0 1 1 1 0 0 1 1 0]

=== PROBABILITAS ===
[[9.99661752e-01 3.38247789e-04]
 [9.71238642e-01 2.87613579e-02]
 [9.15902569e-01 8.40974311e-02]
 [7.15347905e-02 9.28465209e-01]
 [1.20704723e-02 9.87929528e-01]
 [9.96057000e-01 3.94300020e-03]
 [9.98744711e-01 1.25528923e-03]
 [7.32686907e-01 2.67313093e-01]
 [8.16006497e-01 1.83993503e-01]
 [2.36051211e-01 7.63948789e-01]
 [7.16299729e-01 2.