<a href="https://colab.research.google.com/github/asrianda/matakuliah/blob/main/Kecerdasan_K_MTI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import MinMaxScaler

# Dataset
X = np.array([
    [2, 60, 50],
    [3, 65, 55],
    [4, 70, 60],
    [5, 75, 65],
    [6, 80, 70],
    [7, 85, 75],
    [8, 90, 80],
    [1, 50, 45],
    [9, 95, 85],
    [10, 98, 90]
])

y = np.array([0,0,0,1,1,1,1,0,1,1])

# Normalisasi (lebih standar pakai scaler)
scaler = MinMaxScaler()
X = scaler.fit_transform(X)

# Model Neural Network
model = MLPClassifier(
    hidden_layer_sizes=(4,),   # 1 hidden layer, 4 neuron
    activation='relu',
    solver='adam',
    max_iter=1000,
    random_state=42
)

# Training
model.fit(X, y)

# Prediksi
pred = model.predict(X)

# Probabilitas
prob = model.predict_proba(X)

print("Probabilitas:")
print(prob)

print("\nPrediksi kelas:")
print(pred)

Probabilitas:
[[0.87135617 0.12864383]
 [0.74382898 0.25617102]
 [0.55451456 0.44548544]
 [0.34793947 0.65206053]
 [0.18616167 0.81383833]
 [0.08930232 0.91069768]
 [0.05898293 0.94101707]
 [0.93075015 0.06924985]
 [0.03852402 0.96147598]
 [0.02535707 0.97464293]]

Prediksi kelas:
[0 0 0 1 1 1 1 0 1 1]


/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


## **Neural Network**

In [2]:
import numpy as np

# Dataset
X = np.array([
    [2, 60, 50],
    [3, 65, 55],
    [4, 70, 60],
    [5, 75, 65],
    [6, 80, 70],
    [7, 85, 75],
    [8, 90, 80],
    [1, 50, 45],
    [9, 95, 85],
    [10, 98, 90]
])

y = np.array([[0],[0],[0],[1],[1],[1],[1],[0],[1],[1]])

# Normalisasi
X = X / np.max(X, axis=0)

# Inisialisasi bobot
np.random.seed(1)
weights_input_hidden = np.random.rand(3, 2)
weights_hidden_output = np.random.rand(2, 1)

bias_hidden = np.random.rand(1, 2)
bias_output = np.random.rand(1, 1)

# Fungsi aktivasi
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Training
epochs = 5000
lr = 0.1

for i in range(epochs):

    # FORWARD
    hidden = sigmoid(np.dot(X, weights_input_hidden) + bias_hidden)
    output = sigmoid(np.dot(hidden, weights_hidden_output) + bias_output)

    # ERROR
    error = y - output

    # BACKPROPAGATION
    d_output = error * sigmoid_derivative(output)
    d_hidden = d_output.dot(weights_hidden_output.T) * sigmoid_derivative(hidden)

    # UPDATE
    weights_hidden_output += hidden.T.dot(d_output) * lr
    weights_input_hidden += X.T.dot(d_hidden) * lr

    bias_output += np.sum(d_output, axis=0) * lr
    bias_hidden += np.sum(d_hidden, axis=0) * lr

# HASIL
print("Output prediksi:")
print(output)

print("\nPrediksi kelas:")
print((output > 0.5).astype(int))

Output prediksi:
[[0.00729707]
 [0.02461055]
 [0.19252006]
 [0.81844134]
 [0.98147281]
 [0.99557942]
 [0.99787929]
 [0.00395728]
 [0.99855846]
 [0.9988444 ]]

Prediksi kelas:
[[0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]]
